import { applyProductLocale } from "./locale-names";
import type { Product, Variant } from "./types";

function variants(
  prefix: string,
  sizes: string[],
  colors: { color: string; hex: string; price?: number; stock?: number }[],
  price: number,
  stock = 4,
): Variant[] {
  const out: Variant[] = [];
  for (const size of sizes) {
    for (const c of colors) {
      const code = `${prefix}-${size}-${c.color.slice(0, 3).toUpperCase()}`;
      out.push({
        sku: code,
        size,
        color: c.color,
        hex: c.hex,
        price: c.price ?? price,
        stock: c.stock ?? stock,
      });
    }
  }
  return out;
}

const SML = ["S", "M", "L"];
const MLXL = ["M", "L", "XL"];
const FREE = ["Free Size"];
const KIDS = ["3-4Y", "5-6Y", "7-8Y"];
const SHOE = ["6", "7", "8"];
const SOCK = ["Free Size"];
const BLOUSE = ["34", "36", "38", "40"];

const RAW_PRODUCTS: Product[] = [
  {
    id: "tsh-sunflower-01",
    name: "Sunflower Print Cotton T-Shirt",
    brand: "Anouk",
    category: "tshirt",
    fabric: "100% combed cotton",
    fabricWeightGsm: 180,
    basePrice: 599,
    description:
      "A relaxed white cotton tee with one large mustard-yellow sunflower printed in the centre of the chest. The flower has a dark brown seed disc and twelve petals.",
    print: {
      type: "floral",
      flower: "sunflower",
      placement: "chest-center",
      scale: "large",
      motifColor: "mustard yellow",
      motifHex: "#E3A008",
    },
    neckline: "round",
    sleeve: "short",
    fit: "relaxed",
    occasion: "everyday",
    care: "machine wash cold, tumble dry low",
    aliases: [
      "sunflower tshirt",
      "phool wali tshirt",
      "yellow flower shirt",
      "surajmukhi",
      "the sunflower one",
      "the yellow flower one",
    ],
    variants: variants("TSH-SF-01", SML, [
      { color: "white", hex: "#F7F4EE" },
      { color: "black", hex: "#1A1A1A", price: 649, stock: 0 },
    ], 599, 5),
  },
  {
    id: "tsh-rose-01",
    name: "Rose Print Cotton T-Shirt",
    brand: "Anouk",
    category: "tshirt",
    fabric: "100% combed cotton",
    fabricWeightGsm: 180,
    basePrice: 599,
    description:
      "Same cut as the sunflower tee, but the chest print is a single deep-pink rose with two leaves. No writing.",
    print: {
      type: "floral",
      flower: "rose",
      placement: "chest-center",
      scale: "large",
      motifColor: "deep pink",
      motifHex: "#C73B5C",
    },
    neckline: "round",
    sleeve: "short",
    fit: "relaxed",
    occasion: "everyday",
    care: "machine wash cold, tumble dry low",
    aliases: [
      "rose tshirt",
      "gulab wali tshirt",
      "pink flower shirt",
      "the rose one",
      "phool wali shirt",
    ],
    variants: variants("TSH-RS-01", SML, [
      { color: "white", hex: "#F7F4EE" },
      { color: "blush", hex: "#F3D6D8" },
    ], 599, 4),
  },
  {
    id: "tsh-quote-01",
    name: "Live Laugh Love Print T-Shirt",
    brand: "Anouk",
    category: "tshirt",
    fabric: "100% combed cotton",
    fabricWeightGsm: 180,
    basePrice: 599,
    description:
      "Same cut and price as the flower tees. Chest print is the exact words “Live, Laugh, Love” in rose-gold script lettering. No flowers.",
    print: {
      type: "text",
      quote: "Live, Laugh, Love",
      quoteFont: "script",
      placement: "chest-center",
      scale: "medium",
      motifColor: "rose gold",
      motifHex: "#B76E79",
    },
    neckline: "round",
    sleeve: "short",
    fit: "relaxed",
    occasion: "everyday",
    care: "machine wash cold, tumble dry low",
    aliases: [
      "live laugh love",
      "quote tshirt",
      "likha hua tshirt",
      "the one with writing on it",
      "word wali shirt",
      "the shirt with writing",
    ],
    variants: variants("TSH-QT-01", SML, [
      { color: "white", hex: "#F7F4EE" },
      { color: "cream", hex: "#F0E6D2" },
    ], 599, 6),
  },
  {
    id: "kurta-biba-straight-01",
    name: "Biba Cotton Straight Kurta",
    brand: "Biba",
    category: "kurta",
    fabric: "100% cotton",
    fabricWeightGsm: 140,
    basePrice: 1299,
    description:
      "A plain everyday cotton straight kurta with a mandarin collar, full sleeves, and two side pockets. No print — the colour is the look.",
    print: {
      type: "solid",
      placement: "all-over",
      scale: "medium",
      motifColor: "none",
      motifHex: "#4C3D8A",
    },
    neckline: "mandarin",
    sleeve: "full",
    fit: "straight",
    lengthInches: 42,
    closure: "front-buttons",
    pockets: true,
    occasion: "everyday",
    care: "machine wash cold, do not bleach",
    aliases: [
      "plain kurta",
      "simple kurta",
      "cotton kurta",
      "full sleeve white kurta",
      "biba kurta",
      "sidha kurta",
    ],
    variants: variants(
      "KUR-BB-01",
      MLXL,
      [
        { color: "indigo", hex: "#3D4F7C" },
        { color: "maroon", hex: "#7A2430" },
        { color: "cream", hex: "#EFE6D2" },
      ],
      1299,
      4,
    ),
  },
  {
    id: "kurta-chikan-yoke-01",
    name: "Chikankari Kurta — Yoke Embroidery",
    brand: "Fabindia",
    category: "kurta",
    fabric: "cotton mulmul",
    fabricWeightGsm: 90,
    basePrice: 2199,
    description:
      "White mulmul kurta with white chikankari only on the yoke (the panel from the collarbone down to the chest). Sleeves and hem are plain.",
    print: {
      type: "embroidered",
      motif: "chikankari vine",
      placement: "yoke",
      scale: "small",
      motifColor: "ivory white",
      motifHex: "#F5F1E8",
    },
    embroidery: {
      style: "chikankari",
      where: "yoke only",
      threadColor: "ivory white",
    },
    neckline: "round",
    sleeve: "three-quarter",
    fit: "straight",
    lengthInches: 44,
    closure: "front-buttons",
    occasion: "festive",
    care: "hand wash separately, dry in shade",
    aliases: [
      "chikankari kurta",
      "chikan kurta",
      "white embroidery kurta",
      "yoke wali kurta",
      "the one with embroidery on the chest",
      "lucknowi kurta",
    ],
    variants: variants("KUR-CK-Y", MLXL, [{ color: "white", hex: "#F8F5EE" }], 2199, 3),
  },
  {
    id: "kurta-chikan-sleeve-01",
    name: "Chikankari Kurta — Sleeve and Hem Embroidery",
    brand: "Fabindia",
    category: "kurta",
    fabric: "cotton mulmul",
    fabricWeightGsm: 90,
    basePrice: 2299,
    description:
      "Same white mulmul as the yoke kurta, but the chikankari runs along the sleeves and the hem. The chest and yoke are plain.",
    print: {
      type: "embroidered",
      motif: "chikankari vine",
      placement: "sleeve",
      scale: "small",
      motifColor: "ivory white",
      motifHex: "#F5F1E8",
    },
    embroidery: {
      style: "chikankari",
      where: "sleeves and hem",
      threadColor: "ivory white",
    },
    neckline: "round",
    sleeve: "three-quarter",
    fit: "straight",
    lengthInches: 44,
    closure: "front-buttons",
    occasion: "festive",
    care: "hand wash separately, dry in shade",
    aliases: [
      "chikankari kurta",
      "chikan kurta",
      "sleeve embroidery kurta",
      "the one with embroidery on the sleeves",
      "haath wali chikan",
    ],
    variants: variants("KUR-CK-S", MLXL, [{ color: "white", hex: "#F8F5EE" }], 2299, 3),
  },
  {
    id: "kurta-mango-buti-01",
    name: "Tiny Mango Buti Print Kurta",
    brand: "W",
    category: "kurta",
    fabric: "cotton cambric",
    fabricWeightGsm: 120,
    basePrice: 1499,
    description:
      "Mustard cotton kurta covered in tiny mango buti (paisley-seed) prints, each smaller than a thumbnail, all over the body.",
    print: {
      type: "block-print",
      motif: "mango buti",
      placement: "all-over",
      scale: "tiny",
      motifColor: "rust",
      motifHex: "#A64B2A",
    },
    neckline: "round",
    sleeve: "three-quarter",
    fit: "A-line",
    lengthInches: 44,
    pockets: true,
    occasion: "everyday",
    care: "machine wash cold",
    aliases: [
      "buti kurta",
      "booti",
      "mango print kurta",
      "tiny print kurta",
      "chhota booti",
      "aam booti",
    ],
    variants: variants("KUR-MB-01", MLXL, [
      { color: "mustard", hex: "#D4A017" },
      { color: "sage", hex: "#8A9A6A" },
    ], 1499, 4),
  },
  {
    id: "kurta-paisley-back-01",
    name: "Oversized Paisley Back Kurta",
    brand: "W",
    category: "kurta",
    fabric: "cotton cambric",
    fabricWeightGsm: 120,
    basePrice: 1599,
    description:
      "Plain sage kurta from the front. One oversized navy paisley covering most of the back. No other print.",
    print: {
      type: "paisley",
      motif: "paisley",
      placement: "back",
      scale: "oversized",
      motifColor: "navy",
      motifHex: "#1E3A5F",
    },
    neckline: "round",
    sleeve: "three-quarter",
    fit: "A-line",
    lengthInches: 44,
    pockets: true,
    occasion: "everyday",
    care: "machine wash cold",
    aliases: [
      "paisley kurta",
      "back print kurta",
      "the one with the big print on the back",
      "peechhe wala print",
      "keri print",
    ],
    variants: variants("KUR-PL-01", MLXL, [{ color: "sage", hex: "#8A9A6A" }], 1599, 3),
  },
  {
    id: "saree-cotton-01",
    name: "Handloom Cotton Saree with Marigold Border",
    brand: "Nalli",
    category: "saree",
    fabric: "handloom cotton",
    fabricWeightGsm: 110,
    basePrice: 899,
    description:
      "Everyday six-yard cotton saree. Body is unbleached off-white. A two-inch marigold (genda) floral border runs along both long edges. Pallu is plain.",
    print: {
      type: "floral",
      flower: "marigold",
      placement: "border",
      scale: "small",
      motifColor: "marigold orange",
      motifHex: "#E07A14",
    },
    lengthInches: 216,
    occasion: "everyday",
    care: "machine wash gentle, dry in shade",
    aliases: [
      "cotton saree",
      "sari",
      "genda print",
      "marigold saree",
      "border wali saree",
      "roz marne wali saree",
      "sasta cotton saree",
    ],
    variants: variants("SAR-CT-01", FREE, [
      { color: "off-white", hex: "#F3EBDA" },
      { color: "sky blue", hex: "#C5D7E8" },
    ], 899, 8),
  },
  {
    id: "saree-silk-01",
    name: "Kanjeevaram Silk Saree with Lotus Pallu",
    brand: "Nalli",
    category: "saree",
    fabric: "pure kanjeevaram silk",
    fabricWeightGsm: 180,
    basePrice: 4499,
    description:
      "Wedding-weight silk saree. Body is deep maroon with a gold zari temple border. The pallu has three large lotus flowers in gold zari.",
    print: {
      type: "embroidered",
      flower: "lotus",
      motif: "lotus",
      placement: "pallu",
      scale: "large",
      motifColor: "gold zari",
      motifHex: "#C9A227",
    },
    embroidery: {
      style: "zari",
      where: "pallu and temple border",
      threadColor: "gold",
    },
    occasion: "wedding",
    care: "dry clean only",
    aliases: [
      "silk saree",
      "kanjeevaram",
      "kanjivaram",
      "lotus saree",
      "kamal pallu",
      "shaadi wali saree",
      "zari saree",
    ],
    variants: variants("SAR-SL-01", FREE, [
      { color: "maroon", hex: "#6E1A28" },
      { color: "peacock green", hex: "#0F4C3A" },
    ], 4499, 2),
  },
  {
    id: "salwar-marigold-01",
    name: "Marigold Print Salwar Suit Set",
    brand: "Biba",
    category: "salwar",
    fabric: "cotton",
    fabricWeightGsm: 130,
    basePrice: 1899,
    description:
      "Three-piece set: kurta, salwar, and dupatta. Kurta has medium marigold flowers printed all over. Dupatta is plain mustard. Salwar is plain cream.",
    print: {
      type: "floral",
      flower: "marigold",
      placement: "all-over",
      scale: "medium",
      motifColor: "marigold orange",
      motifHex: "#E07A14",
    },
    neckline: "round",
    sleeve: "three-quarter",
    fit: "straight",
    occasion: "festive",
    care: "machine wash cold",
    aliases: [
      "salwar suit",
      "suit set",
      "genda suit",
      "marigold suit",
      "three piece",
      "salwar kameez",
    ],
    variants: variants("SAL-MG-01", MLXL, [
      { color: "mustard", hex: "#D4A017" },
      { color: "cream", hex: "#EFE6D2" },
    ], 1899, 3),
  },
  {
    id: "nighty-libas-01",
    name: "Libas Floral Cotton Nighty",
    brand: "Libas",
    category: "nighty",
    fabric: "soft cotton",
    fabricWeightGsm: 120,
    basePrice: 799,
    description:
      "Full-length button-front nighty. Small jasmine (chameli) flowers printed all over on a mint ground. Short sleeves. Two pockets.",
    print: {
      type: "floral",
      flower: "jasmine",
      placement: "all-over",
      scale: "small",
      motifColor: "white",
      motifHex: "#FFFFFF",
    },
    neckline: "V-neck",
    sleeve: "short",
    fit: "relaxed",
    lengthInches: 50,
    closure: "front-buttons",
    pockets: true,
    occasion: "sleepwear",
    care: "machine wash cold",
    aliases: [
      "nighty",
      "nightdress",
      "libas nighty",
      "chameli nighty",
      "jasmine nighty",
      "sona wali nighty",
    ],
    variants: variants("NTY-LB-01", MLXL, [
      { color: "mint", hex: "#C8E0D0" },
      { color: "lilac", hex: "#D7CDE8" },
    ], 799, 5),
  },
  {
    id: "nighty-zola-01",
    name: "Zola Floral Cotton Nighty",
    brand: "Zola",
    category: "nighty",
    fabric: "soft cotton",
    fabricWeightGsm: 120,
    basePrice: 749,
    description:
      "Nearly the same cut as the Libas nighty — button-front, short sleeves, two pockets — but the print is tiny daisies, not jasmine, and the brand is Zola.",
    print: {
      type: "floral",
      flower: "daisy",
      placement: "all-over",
      scale: "tiny",
      motifColor: "white",
      motifHex: "#FFFFFF",
    },
    neckline: "V-neck",
    sleeve: "short",
    fit: "relaxed",
    lengthInches: 50,
    closure: "front-buttons",
    pockets: true,
    occasion: "sleepwear",
    care: "machine wash cold",
    aliases: [
      "nighty",
      "zola nighty",
      "daisy nighty",
      "the cheaper nighty",
      "gudiya phool nighty",
    ],
    variants: variants("NTY-ZL-01", MLXL, [
      { color: "mint", hex: "#C8E0D0" },
      { color: "peach", hex: "#F2CFB8" },
    ], 749, 6),
  },
  {
    id: "nightsuit-polka-01",
    name: "Polka Dot Cotton Night Suit",
    brand: "Libas",
    category: "nightsuit",
    fabric: "cotton jersey",
    fabricWeightGsm: 160,
    basePrice: 999,
    description:
      "Two-piece night suit: round-neck top and elastic pants. Small navy polka dots on a cream ground. No flowers, no writing.",
    print: {
      type: "polka",
      motif: "polka dots",
      placement: "all-over",
      scale: "small",
      motifColor: "navy",
      motifHex: "#1E3A5F",
    },
    neckline: "round",
    sleeve: "short",
    fit: "relaxed",
    occasion: "sleepwear",
    care: "machine wash cold",
    aliases: [
      "night suit",
      "pyjama set",
      "polka",
      "bindi wali suit",
      "dot wali night suit",
      "nightsuit",
    ],
    variants: variants("NSU-PK-01", MLXL, [{ color: "cream", hex: "#EFE6D2" }], 999, 4),
  },
  {
    id: "shawl-wool-01",
    name: "Merino Wool Shawl with Phulkari Ends",
    brand: "Pashmina House",
    category: "shawl",
    fabric: "100% merino wool",
    fabricWeightGsm: 220,
    basePrice: 2499,
    description:
      "Warm merino shawl, 80 by 28 inches. Body is solid charcoal. Both short ends have a four-inch phulkari band of red and gold flowers.",
    print: {
      type: "embroidered",
      flower: "marigold",
      motif: "phulkari band",
      placement: "border",
      scale: "medium",
      motifColor: "red and gold",
      motifHex: "#C0392B",
    },
    embroidery: {
      style: "phulkari",
      where: "both short ends",
      threadColor: "red and gold",
    },
    occasion: "winter",
    care: "dry clean only",
    aliases: [
      "wool shawl",
      "pashmina",
      "phulkari shawl",
      "garam shawl",
      "oon wali shawl",
      "winter shawl",
    ],
    variants: variants("SHW-WL-01", FREE, [
      { color: "charcoal", hex: "#3A3A3A" },
      { color: "wine", hex: "#5C1F2A" },
    ], 2499, 3),
  },
  {
    id: "shawl-acrylic-01",
    name: "Acrylic Shawl with Plain Border",
    brand: "Pashmina House",
    category: "shawl",
    fabric: "acrylic knit",
    fabricWeightGsm: 180,
    basePrice: 699,
    description:
      "Looks similar to the wool shawl from a distance but is acrylic, lighter, and cheaper. Solid body, plain 1-inch hem, no embroidery.",
    print: {
      type: "solid",
      placement: "all-over",
      scale: "medium",
      motifColor: "none",
      motifHex: "#3A3A3A",
    },
    occasion: "winter",
    care: "machine wash cold, do not tumble dry",
    aliases: [
      "acrylic shawl",
      "sasta shawl",
      "plain shawl",
      "light shawl",
      "synthetic shawl",
    ],
    variants: variants("SHW-AC-01", FREE, [
      { color: "charcoal", hex: "#3A3A3A" },
      { color: "beige", hex: "#CDB89A" },
    ], 699, 7),
  },
  {
    id: "cardigan-hibiscus-01",
    name: "Hibiscus Knit Cardigan",
    brand: "Global Desi",
    category: "cardigan",
    fabric: "cotton-acrylic knit",
    fabricWeightGsm: 240,
    basePrice: 1699,
    description:
      "Button-front cardigan. One hibiscus flower embroidered on the left chest, about the size of a palm. Full sleeves. Two pockets.",
    print: {
      type: "floral",
      flower: "hibiscus",
      placement: "chest-center",
      scale: "medium",
      motifColor: "coral",
      motifHex: "#E05A4F",
    },
    neckline: "V-neck",
    sleeve: "full",
    fit: "regular",
    closure: "front-buttons",
    pockets: true,
    occasion: "winter",
    care: "hand wash, dry flat",
    aliases: [
      "cardigan",
      "sweater",
      "hibiscus cardigan",
      "gudhal",
      "button wali sweater",
      "the flower sweater",
    ],
    variants: variants("CRD-HB-01", MLXL, [
      { color: "cream", hex: "#EFE6D2" },
      { color: "navy", hex: "#1E3A5F" },
    ], 1699, 3),
  },
  {
    id: "thermal-01",
    name: "Cotton Thermal Innerwear Set",
    brand: "Jockey",
    category: "thermal",
    fabric: "cotton-spandex",
    fabricWeightGsm: 200,
    basePrice: 899,
    description:
      "Two-piece thermal set for under clothes. Round neck top and full-length bottoms. Solid colour, no print, no embroidery.",
    print: {
      type: "solid",
      placement: "all-over",
      scale: "medium",
      motifColor: "none",
      motifHex: "#E8D9C5",
    },
    neckline: "round",
    sleeve: "full",
    fit: "regular",
    occasion: "winter",
    care: "machine wash warm",
    aliases: [
      "thermal",
      "inner",
      "winter inner",
      "banyan thermal",
      "garmi kapda",
      "andar ka sweater",
    ],
    variants: variants("THM-JK-01", MLXL, [
      { color: "beige", hex: "#E8D9C5" },
      { color: "grey", hex: "#8A8A8A" },
    ], 899, 8),
  },
  {
    id: "petticoat-01",
    name: "Cotton Saree Petticoat",
    brand: "Nalli",
    category: "petticoat",
    fabric: "cotton satin",
    fabricWeightGsm: 130,
    basePrice: 349,
    description:
      "Drawstring petticoat to wear under a saree. Solid colour. Side slit for the pallu tuck. No print.",
    print: {
      type: "solid",
      placement: "all-over",
      scale: "medium",
      motifColor: "none",
      motifHex: "#F3EBDA",
    },
    closure: "tie-up",
    occasion: "everyday",
    care: "machine wash warm",
    aliases: [
      "petticoat",
      "saree petticoat",
      "in-skirt",
      "saya",
      "underskirt",
    ],
    variants: variants("PET-NL-01", ["M", "L", "XL", "XXL"], [
      { color: "white", hex: "#F8F5EE" },
      { color: "black", hex: "#1A1A1A" },
      { color: "maroon", hex: "#6E1A28" },
    ], 349, 10),
  },
  {
    id: "blouse-lotus-01",
    name: "Lotus Zari Blouse",
    brand: "Nalli",
    category: "blouse",
    fabric: "silk blend",
    fabricWeightGsm: 150,
    basePrice: 1299,
    description:
      "Sleeveless boat-neck blouse. A small lotus in gold zari sits at the centre of the back. Front is plain. Padded.",
    print: {
      type: "embroidered",
      flower: "lotus",
      motif: "lotus",
      placement: "back",
      scale: "small",
      motifColor: "gold zari",
      motifHex: "#C9A227",
    },
    embroidery: {
      style: "zari",
      where: "centre of the back",
      threadColor: "gold",
    },
    neckline: "boat",
    sleeve: "sleeveless",
    fit: "regular",
    closure: "front-buttons",
    occasion: "festive",
    care: "dry clean only",
    aliases: [
      "blouse",
      "saree blouse",
      "lotus blouse",
      "kamal blouse",
      "back design blouse",
      "choli",
    ],
    variants: variants("BLS-LT-01", BLOUSE, [
      { color: "maroon", hex: "#6E1A28" },
      { color: "gold", hex: "#C9A227" },
    ], 1299, 3),
  },
  {
    id: "dupatta-mirror-01",
    name: "Mirror-Work Dupatta",
    brand: "Global Desi",
    category: "dupatta",
    fabric: "cotton voile",
    fabricWeightGsm: 80,
    basePrice: 799,
    description:
      "2.25 metre dupatta. Tiny mirrors (sheesha) sewn along a two-inch border on all four sides. Body is plain indigo. No flowers.",
    print: {
      type: "embroidered",
      motif: "mirror work",
      placement: "border",
      scale: "small",
      motifColor: "silver mirror",
      motifHex: "#C0C0C0",
    },
    embroidery: {
      style: "mirror-work",
      where: "all four borders",
      threadColor: "silver",
    },
    occasion: "festive",
    care: "hand wash, do not wring",
    aliases: [
      "dupatta",
      "chunri",
      "mirror dupatta",
      "sheesha",
      "the one with mirror work",
      "sheeshe wali dupatta",
    ],
    variants: variants("DUP-MR-01", FREE, [
      { color: "indigo", hex: "#3D4F7C" },
      { color: "red", hex: "#A33B3B" },
    ], 799, 5),
  },
  {
    id: "socks-stripe-01",
    name: "Striped Cotton Ankle Socks (Pack of 3)",
    brand: "Jockey",
    category: "socks",
    fabric: "cotton",
    fabricWeightGsm: 140,
    basePrice: 299,
    description:
      "Pack of three ankle socks. Thin navy and white stripes. No writing, no flowers.",
    print: {
      type: "stripes",
      motif: "thin stripes",
      placement: "all-over",
      scale: "tiny",
      motifColor: "navy",
      motifHex: "#1E3A5F",
    },
    occasion: "everyday",
    care: "machine wash warm",
    aliases: [
      "socks",
      "moze",
      "ankle socks",
      "striped socks",
      "teen wali socks",
    ],
    variants: variants("SOK-ST-01", SOCK, [
      { color: "navy-white", hex: "#1E3A5F" },
      { color: "black-grey", hex: "#2A2A2A" },
    ], 299, 12),
  },
  {
    id: "slippers-01",
    name: "Closed-Toe House Slippers",
    brand: "Bata",
    category: "slippers",
    fabric: "terry cloth upper, rubber sole",
    basePrice: 449,
    description:
      "Indoor slippers with a closed toe and a rubber sole that will not slip on tiles. Solid colour. No print.",
    print: {
      type: "solid",
      placement: "all-over",
      scale: "medium",
      motifColor: "none",
      motifHex: "#7A5C45",
    },
    occasion: "everyday",
    care: "wipe with a damp cloth",
    aliases: [
      "slippers",
      "chappal",
      "ghar wali chappal",
      "house slippers",
      "indoor slippers",
    ],
    variants: variants("SLP-BT-01", SHOE, [
      { color: "brown", hex: "#7A5C45" },
      { color: "navy", hex: "#1E3A5F" },
    ], 449, 6),
  },
  {
    id: "mens-kurta-01",
    name: "Men's Cotton Kurta with Mandarin Collar",
    brand: "Manyavar",
    category: "mens-kurta",
    fabric: "cotton",
    fabricWeightGsm: 140,
    basePrice: 1199,
    description:
      "Straight men's kurta for gifting. Mandarin collar, full sleeves, two pockets. Tiny checks — not floral, not a quote.",
    print: {
      type: "checks",
      motif: "tiny windowpane check",
      placement: "all-over",
      scale: "tiny",
      motifColor: "white",
      motifHex: "#F7F4EE",
    },
    neckline: "mandarin",
    sleeve: "full",
    fit: "straight",
    lengthInches: 42,
    pockets: true,
    occasion: "festive",
    care: "machine wash cold",
    aliases: [
      "mens kurta",
      "mardana kurta",
      "gift kurta",
      "husband kurta",
      "son kurta",
      "manyavar kurta",
    ],
    variants: variants("MKR-MN-01", ["M", "L", "XL", "XXL"], [
      { color: "ivory", hex: "#F4EFE3" },
      { color: "sage", hex: "#8A9A6A" },
    ], 1199, 4),
  },
  {
    id: "kids-tee-01",
    name: "Kids Tee — Nana's Favourite",
    brand: "Anouk Kids",
    category: "kids-tee",
    fabric: "100% cotton",
    fabricWeightGsm: 160,
    basePrice: 399,
    description:
      "Children's round-neck tee. The exact words “Nana's Favourite” are printed across the chest in chunky block letters. No flowers.",
    print: {
      type: "text",
      quote: "Nana's Favourite",
      quoteFont: "block",
      placement: "chest-center",
      scale: "medium",
      motifColor: "navy",
      motifHex: "#1E3A5F",
    },
    neckline: "round",
    sleeve: "short",
    fit: "regular",
    occasion: "everyday",
    care: "machine wash warm",
    aliases: [
      "kids tshirt",
      "bachchon ki tshirt",
      "nana favourite",
      "nana's favourite",
      "gift for grandson",
      "the one that says nana",
    ],
    variants: variants("KID-NF-01", KIDS, [
      { color: "yellow", hex: "#E8C547" },
      { color: "white", hex: "#F7F4EE" },
    ], 399, 5),
  },
  {
    id: "kurta-set-jasmine-01",
    name: "Jasmine Printed Kurta Set with Dupatta",
    brand: "Biba",
    category: "kurta",
    fabric: "cotton",
    fabricWeightGsm: 125,
    basePrice: 2099,
    description:
      "Kurta plus matching palazzo and a chiffon dupatta. Small jasmine sprays printed only on the sleeves of the kurta. Body of the kurta is solid cream.",
    print: {
      type: "floral",
      flower: "jasmine",
      placement: "sleeve",
      scale: "small",
      motifColor: "ivory",
      motifHex: "#F5F1E8",
    },
    neckline: "round",
    sleeve: "three-quarter",
    fit: "straight",
    lengthInches: 44,
    pockets: true,
    occasion: "festive",
    care: "machine wash cold, dry in shade",
    aliases: [
      "kurta set",
      "jasmine kurta",
      "chameli set",
      "sleeve print kurta",
      "the one with flowers on the sleeves",
      "palazzo set",
    ],
    variants: variants("KST-JS-01", MLXL, [
      { color: "cream", hex: "#EFE6D2" },
      { color: "blush", hex: "#F3D6D8" },
    ], 2099, 3),
  },
];

export const PRODUCTS: Product[] = RAW_PRODUCTS.map(applyProductLocale);

export const CATEGORY_LABELS: Record<Product["category"], string> = {
  kurta: "Kurtas",
  saree: "Sarees",
  tshirt: "T-shirts",
  nighty: "Nighties",
  nightsuit: "Night suits",
  salwar: "Salwar suits",
  shawl: "Shawls",
  cardigan: "Cardigans",
  thermal: "Thermals",
  petticoat: "Petticoats",
  blouse: "Blouses",
  dupatta: "Dupattas",
  socks: "Socks",
  slippers: "Slippers",
  "mens-kurta": "Men's kurtas",
  "kids-tee": "Kids",
};

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getVariant(sku: string): { product: Product; variant: Variant } | undefined {
  for (const product of PRODUCTS) {
    const variant = product.variants.find((v) => v.sku === sku);
    if (variant) return { product, variant };
  }
  return undefined;
}

export function inStockVariants(product: Product) {
  return product.variants.filter((v) => v.stock > 0);
}

export function availableSizes(product: Product, color?: string) {
  return [
    ...new Set(
      inStockVariants(product)
        .filter((v) => !color || v.color.toLowerCase() === color.toLowerCase())
        .map((v) => v.size),
    ),
  ];
}

export function availableColors(product: Product, size?: string) {
  const colors = inStockVariants(product)
    .filter((v) => !size || v.size.toLowerCase() === size.toLowerCase())
    .map((v) => ({ color: v.color, hex: v.hex }));
  const seen = new Set<string>();
  return colors.filter((c) => {
    if (seen.has(c.color)) return false;
    seen.add(c.color);
    return true;
  });
}

export function findVariant(product: Product, size?: string, color?: string) {
  const matches = inStockVariants(product).filter((v) => {
    const sizeOk = !size || v.size.toLowerCase() === size.toLowerCase();
    const colorOk = !color || v.color.toLowerCase() === color.toLowerCase();
    return sizeOk && colorOk;
  });
  return matches;
}
